In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# to save txt file using numpy

In [3]:
a=np.array([2,3,4,5])
np.savetxt("text.txt",a)

In [4]:
y=np.loadtxt("text.txt")
print(y)

[2. 3. 4. 5.]


# To iterate the array

In [10]:
a= np.arange(12).reshape(3,4)
print(a)
print()

# To print row wise
for row in a:
    print(row)
    
print()
# To print each cell
for row in a:
    for cell in row:
        print(cell)
        
print()
print()

for cell in a.flat:
    print(cell)
    
print()
print()
for cell in a.flatten():
    print(cell)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

0
1
2
3
4
5
6
7
8
9
10
11


0
1
2
3
4
5
6
7
8
9
10
11


0
1
2
3
4
5
6
7
8
9
10
11


In [15]:
# Numpy offer more sofisticed function call "nditer" to iterate the array
for x in np.nditer(a,order='C'):
    print(x)

print()
for x in np.nditer(a,order='A'):
    print(x)
    
print()
for x in np.nditer(a,order='F'):
    print(x)
print()
for x in np.nditer(a,order='K'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11

0
1
2
3
4
5
6
7
8
9
10
11

0
4
8
1
5
9
2
6
10
3
7
11

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [17]:
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=x*x

print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [18]:
b=np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [19]:
# To iterate two or more array simultaneously
# Two array are compatible if either they are equal or one of dimension is 1
for x,y in np.nditer([a,b]):
    print(x,y)


0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2
