# Numpy: Basic array operation

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [25]:
# one dimension array
a1= np.array([1,3,4,5])
print(a1.ndim)
#Two dimension array
a2=np.array([[2,3],[3],[2,3,4],[2,3],[2,3,4,5,6]])
# "ndim" to retrun dimension of array
print(a1.ndim)
a2=np.array([[2,3],[3,2],[2,3],[2,3],[2,3]])
print(a2.ndim)
print(a2)

1
1
2
[[2 3]
 [3 2]
 [2 3]
 [2 3]
 [2 3]]


In [26]:
# return byte size of element
print(a1.itemsize)
print(a1.size)

8
4


In [16]:
# to return current datatype of an array
a1.dtype

dtype('int64')

In [18]:
print(a1)

[1 3 4 5]


In [20]:
a1

array([1, 3, 4, 5])

In [32]:
# to change the datatype
a2=np.array([[2,3],[3,2],[2,3],[2,3],[2,3]])
print(a2)
#a2
a2=np.array([[2,3],[3,2],[2,3],[2,3],[2,3]], dtype=np.float64)
print(a2)
a2

[[2 3]
 [3 2]
 [2 3]
 [2 3]
 [2 3]]
[[2. 3.]
 [3. 2.]
 [2. 3.]
 [2. 3.]
 [2. 3.]]


array([[2., 3.],
       [3., 2.],
       [2., 3.],
       [2., 3.],
       [2., 3.]])

In [34]:
# "shape"- to return a*b type dimension (row ,column)

print(a2.shape)

(5, 2)


In [36]:
a2=np.array([[2,3],[3,2],[2,3],[2,3],[2,3]], dtype=complex)
a2

array([[2.+0.j, 3.+0.j],
       [3.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j],
       [2.+0.j, 3.+0.j],
       [2.+0.j, 3.+0.j]])

In [37]:
# to intialize the numpy array

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((4))

array([0., 0., 0., 0.])

In [39]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# range and arange 

l=range(5)
l
print(l)
l[1]

# 5 will not included

a1=np.arange(7)
a1
print(a1)

# arange(start,end,step)
a=np.arange(3,8,2)
a

range(0, 5)
[0 1 2 3 4 5 6]


array([3, 5, 7])

In [5]:
# to generate the no between two number
# np.linspace(start number, stop number,quntitity of number)
# this is called linear sequence of number
print(np.linspace(1,10,10))

print(np.linspace(2,5,20))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2.         2.15789474 2.31578947 2.47368421 2.63157895 2.78947368
 2.94736842 3.10526316 3.26315789 3.42105263 3.57894737 3.73684211
 3.89473684 4.05263158 4.21052632 4.36842105 4.52631579 4.68421053
 4.84210526 5.        ]


In [19]:
# to reshape the array- np.reshape
a= np.array([[2,3],[3,4],[4,5]])
print(a)
print()
print(a.shape)
print()
print(a.reshape(2,3))

print()
print(a.reshape(6,1))
# make sure it is compatible with initail array


# to flaten the array means convert into one dimision array
print()
print(a.ravel())
print()
print(a)

# After all the above operation...original array doesnot affected....It will remain be same

[[2 3]
 [3 4]
 [4 5]]

(3, 2)

[[2 3 3]
 [4 4 5]]

[[2]
 [3]
 [3]
 [4]
 [4]
 [5]]

[2 3 3 4 4 5]

[[2 3]
 [3 4]
 [4 5]]


# Some more operation on array

In [22]:
# To find minimum , Maximimum , sum of all element, sum of all row or column wise

print(a.min())
print()
print(a.max())
print()
print(a.sum())
print()

# axis=1 represent row wise  and axis=0 represent column
print()

print(a.sum(axis=0))
print()
print(a.sum(axis=1))

2

5

21


[ 9 12]

[5 7 9]


In [23]:
# to find squreroot of element of array

print(np.sqrt(a))
print()
print(a)

[[1.41421356 1.73205081]
 [1.73205081 2.        ]
 [2.         2.23606798]]

[[2 3]
 [3 4]
 [4 5]]


In [28]:
# to find Standard Deviation, mean, median etc
print(a.std())
print()
print(a.mean())
print()
print(np.median(a))

0.9574271077563381

3.5

3.5


In [31]:
# to get the matrix product
a=np.array([[2,3],[4,5]])

print(a.dot(a))

[[16 21]
 [28 37]]
