# Numpy: Slicing/Stacking and Indexing with boolean arrays

In [ ]:
# Indexing and Slicing

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [12]:
# normal python -list
n=[4,5,6,7]
print(n[0:2])
print()
print(n[0:3])
print()
print(n[-1])
print()
print(n[-3:-1])


# Now in numpy array
a= np.array([4,5,6,7])
print(a[0:2])
print()
print(a[0:3])
print()
print(a[-1])
print()
print(a[-3:-1])

[4, 5]

[4, 5, 6]

7

[5, 6]
[4 5]

[4 5 6]

7

[5 6]


In [25]:
# two or three D array
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2[2,2])
print()
print(a2[1,2])
print()
print(a2[0:2,2])

print()
print(a2[1,1:2])
print()
print(a2[1,0:2])
print()
print(a2[:,1:3])


9

6

[3 6]

[5]

[4 5]

[[2 3]
 [5 6]
 [8 9]]


# how to iterate through an array

In [29]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])

for row in a2:
    print(row)
    
print()
for row in a:
    print(row)

print()
for cell in a2.flat:
    print(cell)

[1 2 3]
[4 5 6]
[7 8 9]

4
5
6
7

1
2
3
4
5
6
7
8
9


# stacking the arrays

In [34]:
a1=np.arange(6).reshape(2,3)
a2=np.arange(6,12).reshape(2,3)
print(a1)
print()
print(a2)

#vertical stacking
np.vstack((a1,a2))



[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
#horizontal stacking
np.hstack((a1,a2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# Splitting

In [44]:
a1=np.arange(30).reshape(3,10)
print(a1)
print()
print(np.hsplit(a1,2))
print()
print(a1)
print()
print(np.hsplit(a1,5))
print()
result=np.hsplit(a1,5)
print(result[0])
print()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

[array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]]), array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

[array([[ 0,  1],
       [10, 11],
       [20, 21]]), array([[ 2,  3],
       [12, 13],
       [22, 23]]), array([[ 4,  5],
       [14, 15],
       [24, 25]]), array([[ 6,  7],
       [16, 17],
       [26, 27]]), array([[ 8,  9],
       [18, 19],
       [28, 29]])]

[[ 0  1]
 [10 11]
 [20 21]]



In [47]:
# Vertical Split
result=np.vsplit(a1,3)
print(result)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


# indexing with boolean

In [56]:
a=np.arange(15).reshape(3,5)
print(a)
print()

b=a>4
print(b)
print()

# to return the value of element after certain comparision
c=a[b]
print(c)
print()
print(a)
print()

# to replace the element of array which satisfy certain condition
a[b]=-1
print(a[b])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

[ 5  6  7  8  9 10 11 12 13 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
