In [1]:
pip install numpy as np


  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13652 sha256=6ab0463ddab1b27feda672960384497a6c08fdefefa5aa73bf9ca57b157e6956
  Stored in directory: /home/jai/.cache/pip/wheels/8d/31/5b/f3f27c678f2b3ad7e29903ed09bb7446717fd4c8b35f53973a
Successfully built np
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([2,3,4,4])

In [4]:
a

array([2, 3, 4, 4])

In [5]:
a[0]

2

In [6]:
a[2]

4

# the main benefit of numpy array over python list
1) Less Memory
2) Fast
3) Convenient to use

In [7]:
l= range(1000)

In [8]:
a=np.arange(1000)

In [14]:
import sys

In [15]:
print(sys.getsizeof(2)*len(l))

28000


In [12]:
print(a.itemsize*a.size)

8000


In [13]:
print(len(l))

1000


In [16]:
print(sys.getsizeof(4))

28


In [17]:
a.itemsize

8

# Now I am showing that numpy array is fast and convinient as compared to native python list

In [39]:
ls=[2,3,2,5,4]
print(sorted(ls))
ls.sort()
print(ls)
#print(a)

[2, 2, 3, 4, 5]
[2, 2, 3, 4, 5]


In [44]:
import time
start=time.time()
# for time taken by list
size=10
l1=range(size)
l2=range(size)
print([(x1+x2)for x1,x2 in zip(l1,l2)])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [48]:
start=time.time()
# for time taken by list
size=1000
l1=range(size)
l2=range(size)
result=[(x1+x2)for x1,x2 in zip(l1,l2)]
print(time.time()-start)

#for time taken by numpy array
ar1=np.arange(size)
ar2=np.arange(size)
start=time.time()
a=ar1+ar2
print(time.time()-start)


0.0003097057342529297
0.001894235610961914


In [49]:
start=time.time()
# for time taken by list
size=1000000
l1=range(size)
l2=range(size)
result=[(x1+x2)for x1,x2 in zip(l1,l2)]
print(time.time()-start)

#for time taken by numpy array
ar1=np.arange(size)
ar2=np.arange(size)
start=time.time()
a=ar1+ar2
print(time.time()-start)

0.14418625831604004
0.005944252014160156


# arithmetic operation  in numpy array

In [51]:
ar1=np.array([2,3,4,5,6])
ar2=np.array([3,4,3,2,1])
print(ar1+ar2)
print(ar1-ar2)
print(ar1-ar2)

[5 7 7 7 7]
[-1 -1  1  3  5]
